version: "3"

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '81:81' # http://HOST_NAME:81 <- Nginx-proxy-managerアクセスできる
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: '3306'
      DB_MYSQL_USER: 'MYSQL_USER'
      DB_MYSQL_PASSWORD: 'MYSQL_PASSWORD'
      DB_MYSQL_NAME: 'MYSQL_DB_NAME'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    networks:
      - front
      - back

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'YSQL_ROOT_PASSWORD'
      MYSQL_DATABASE: 'MYSQL_DB_NAME'
      MYSQL_USER: 'MYSQL_USER'
      MYSQL_PASSWORD: 'MYSQL_PASSWORD'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - back

volumes:
  data:
  letsencrypt:
  mysql:

networks:
  front:  # docker network create front
    external: true
  back:  # docker network create front

# 参考
# https://qiita.com/nnnue/items/621e5ffebb2f6589e4c5
# セキュリティグループ(ファイアーオール)をカスタムTCPで81番PORTを0.0.0.0/0で開けておく
